package notify

import (
	"bytes"
	"fmt"
	"html/template"
	"strings"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
)

// Subject is the email subject line for an event.
func (e Event) Subject() string {
	return "[Keel] " + e.Title
}

// tone picks the badge text and accent color for an event, matching the
// status colors of the web UI.
func (e Event) tone() (label, color, soft string) {
	switch e.Kind {
	case RunSucceeded:
		return "Succeeded", "#047857", "#ecfdf5"
	case RunFailed:
		return "Failed", "#b91c1c", "#fef2f2"
	case RunCanceled:
		return "Canceled", "#475569", "#f1f5f9"
	case RunStarted:
		return "Started", "#0369a1", "#f0f9ff"
	case "test":
		return "Test", "#0f766e", "#f0fdfa"
	default:
		return Label(string(e.Kind)), "#0f766e", "#f0fdfa"
	}
}

// Text renders the plain-text alternative.
func (e Event) Text() string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n%s\n\n", e.Title, strings.Repeat("=", len([]rune(e.Title))))
	if e.Summary != "" {
		b.WriteString(e.Summary + "\n\n")
	}
	if e.Error != "" {
		fmt.Fprintf(&b, "Error: %s\n\n", e.Error)
	}
	for _, f := range e.Facts {
		fmt.Fprintf(&b, "%-14s %s\n", f.Label+":", f.Value)
	}
	if len(e.Inputs) > 0 {
		b.WriteString("\nDeploy-time inputs:\n")
		for _, f := range e.Inputs {
			fmt.Fprintf(&b, "  %s = %s\n", f.Label, f.Value)
		}
	}
	if e.Insight != "" {
		b.WriteString("\nAI insight\n----------\n")
		b.WriteString(strings.TrimSpace(e.Insight) + "\n")
		b.WriteString("\n(Generated by a language model from the run's log, steps, and non-secret inputs. Check it against the log before acting on anything irreversible.)\n")
	} else if e.InsightNote != "" {
		b.WriteString("\nAI insight: " + e.InsightNote + "\n")
	}
	if len(e.LogTail) > 0 {
		fmt.Fprintf(&b, "\nLast %d log lines:\n", len(e.LogTail))
		b.WriteString(strings.Repeat("-", 40) + "\n")
		for _, l := range e.LogTail {
			b.WriteString(l + "\n")
		}
		b.WriteString(strings.Repeat("-", 40) + "\n")
	}
	if e.Link != "" {
		label := e.LinkLabel
		if label == "" {
			label = "Open in Keel"
		}
		fmt.Fprintf(&b, "\n%s: %s\n", label, e.Link)
	}
	fmt.Fprintf(&b, "\n--\n%s", e.reason())
	if e.SettingsLink != "" {
		fmt.Fprintf(&b, " Manage recipients and events: %s", e.SettingsLink)
	}
	b.WriteString("\n")
	return b.String()
}

// reason tells the reader why the email arrived.
func (e Event) reason() string {
	if info, ok := Lookup(string(e.Kind)); ok {
		return fmt.Sprintf("You receive this because you are subscribed to \u201c%s\u201d events for %s in Keel Cloud.", info.Label, e.OrgName)
	}
	return fmt.Sprintf("Sent from the notification settings of %s in Keel Cloud.", e.OrgName)
}

// md renders the insight's Markdown. Raw HTML is dropped by goldmark's
// default policy, so model output can be inlined safely.
var md = goldmark.New(goldmark.WithExtensions(extension.GFM))

func renderMarkdown(src string) template.HTML {
	var buf bytes.Buffer
	if err := md.Convert([]byte(src), &buf); err != nil {
		return template.HTML(template.HTMLEscapeString(src))
	}
	// Inline styles for email clients, which ignore <style> blocks in many
	// cases: headings become small caps labels, lists and code get spacing.
	out := buf.String()
	out = strings.ReplaceAll(out, "<h2>", `<h2 style="margin:16px 0 4px;font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#5b21b6;">`)
	out = strings.ReplaceAll(out, "<h3>", `<h3 style="margin:14px 0 4px;font-size:13px;font-weight:700;color:#0f172a;">`)
	out = strings.ReplaceAll(out, "<p>", `<p style="margin:4px 0 8px;font-size:14px;line-height:1.55;color:#0f172a;">`)
	out = strings.ReplaceAll(out, "<ul>", `<ul style="margin:4px 0 8px 20px;padding:0;font-size:14px;line-height:1.55;color:#0f172a;">`)
	out = strings.ReplaceAll(out, "<ol>", `<ol style="margin:4px 0 8px 20px;padding:0;font-size:14px;line-height:1.55;color:#0f172a;">`)
	out = strings.ReplaceAll(out, "<li>", `<li style="margin:2px 0;">`)
	out = strings.ReplaceAll(out, "<code>", `<code style="font-family:'JetBrains Mono',ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12px;background:#f1f5f9;border-radius:4px;padding:1px 5px;">`)
	out = strings.ReplaceAll(out, "<pre>", `<pre style="margin:6px 0 10px;padding:10px 12px;background:#020617;color:#e2e8f0;border-radius:8px;font-size:12px;line-height:1.5;white-space:pre-wrap;word-break:break-all;">`)
	out = strings.ReplaceAll(out, "<blockquote>", `<blockquote style="margin:6px 0;padding-left:12px;border-left:3px solid #e2e8f0;color:#475569;">`)
	return template.HTML(out)
}

// emailTmpl is the HTML layout: a transactional email built like a status
// report. Table-based and inline-styled so Gmail, Outlook, and Apple Mail
// render it the same; real headings for assistive technology; text and
// color both carry the status; contrast-checked colors; the primary
// action sits above the long log, and the footer says why the email came.
var emailTmpl = template.Must(template.New("email").Parse(`<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="x-apple-disable-message-reformatting">
<meta name="color-scheme" content="light">
<meta name="supported-color-schemes" content="light">
<title>{{.Title}}</title>
</head>
<body style="margin:0;padding:0;background:#eef2f6;-webkit-font-smoothing:antialiased;">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">{{.Preheader}}&#8199;&#847;&#8199;&#847;&#8199;&#847;&#8199;&#847;&#8199;&#847;&#8199;&#847;</div>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:#eef2f6;">
<tr><td align="center" style="padding:28px 12px;">
<table role="presentation" width="600" cellspacing="0" cellpadding="0" border="0" style="width:600px;max-width:100%;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#0f172a;">

  <tr><td style="padding:0 4px 12px;">
    <table role="presentation" cellspacing="0" cellpadding="0" border="0"><tr>
      <td style="width:24px;height:24px;border-radius:6px;background:#0f172a;text-align:center;vertical-align:middle;color:#ffffff;font-size:13px;font-weight:700;line-height:24px;" aria-hidden="true">K</td>
      <td style="padding-left:9px;font-size:14px;font-weight:600;color:#0f172a;">Keel Cloud</td>
      <td style="padding-left:8px;font-size:14px;color:#64748b;">{{.OrgName}}</td>
    </tr></table>
  </td></tr>

  <tr><td style="background:#ffffff;border:1px solid #d9e0e8;border-radius:10px;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0">

      <tr><td style="padding:26px 28px 8px;">
        <span style="display:inline-block;padding:3px 10px;border-radius:4px;background:{{.Soft}};color:{{.Color}};border:1px solid {{.Color}};font-size:12px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;">{{.Badge}}</span>
        <h1 style="margin:12px 0 6px;font-size:21px;line-height:1.3;font-weight:700;letter-spacing:-.01em;color:#0f172a;">{{.Title}}</h1>
        {{if .Summary}}<p style="margin:0;font-size:15px;line-height:1.55;color:#334155;">{{.Summary}}</p>{{end}}
      </td></tr>

      {{if .Error}}
      <tr><td style="padding:12px 28px 0;">
        <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr>
          <td style="padding:10px 14px;background:#fef2f2;border-left:4px solid #dc2626;border-radius:0 6px 6px 0;">
            <p style="margin:0 0 2px;font-size:11px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:#991b1b;">Error</p>
            <p style="margin:0;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,'Liberation Mono',monospace;font-size:13px;line-height:1.5;color:#7f1d1d;word-break:break-word;">{{.Error}}</p>
          </td>
        </tr></table>
      </td></tr>
      {{end}}

      {{if .Facts}}
      <tr><td style="padding:18px 28px 0;">
        <h2 style="margin:0 0 4px;font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#64748b;">Details</h2>
        <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0">
          {{range .Facts}}
          <tr>
            <th scope="row" align="left" style="padding:8px 16px 8px 0;border-top:1px solid #eef2f6;font-size:13px;font-weight:500;color:#64748b;white-space:nowrap;vertical-align:top;width:120px;">{{.Label}}</th>
            <td style="padding:8px 0;border-top:1px solid #eef2f6;font-size:14px;color:#0f172a;vertical-align:top;word-break:break-word;">{{.Value}}</td>
          </tr>
          {{end}}
        </table>
      </td></tr>
      {{end}}

      {{if .Inputs}}
      <tr><td style="padding:18px 28px 0;">
        <h2 style="margin:0 0 8px;font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#64748b;">Deploy-time inputs</h2>
        {{range .Inputs}}<span style="display:inline-block;margin:0 6px 6px 0;padding:3px 9px;border-radius:5px;background:#f8fafc;border:1px solid #cbd5e1;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,'Liberation Mono',monospace;font-size:12px;color:#0f172a;">{{.Label}}=<b>{{.Value}}</b></span>{{end}}
      </td></tr>
      {{end}}

      {{if .Link}}
      <tr><td style="padding:22px 28px 6px;">
        <table role="presentation" cellspacing="0" cellpadding="0" border="0"><tr>
          <td style="border-radius:7px;background:#0f766e;">
            <a href="{{.Link}}" style="display:inline-block;padding:11px 18px;border-radius:7px;background:#0f766e;color:#ffffff;font-size:14px;font-weight:600;text-decoration:none;">{{.LinkLabel}}</a>
          </td>
        </tr></table>
      </td></tr>
      {{end}}

      {{if .Insight}}
      <tr><td style="padding:20px 28px 0;">
        <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="border:1px solid #ddd6fe;border-radius:8px;">
          <tr><td style="padding:12px 18px;background:#f5f3ff;border-bottom:1px solid #ddd6fe;border-radius:8px 8px 0 0;">
            <h2 style="margin:0;font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#5b21b6;">AI insight</h2>
          </td></tr>
          <tr><td style="padding:12px 18px 14px;">
            {{.Insight}}
          </td></tr>
          <tr><td style="padding:8px 18px 10px;border-top:1px solid #ede9fe;font-size:11px;line-height:1.5;color:#64748b;">Generated by a language model from this run's log, steps, and non-secret inputs. Check it against the log before acting on anything irreversible.</td></tr>
        </table>
      </td></tr>
      {{else if .InsightNote}}
      <tr><td style="padding:16px 28px 0;font-size:12px;line-height:1.5;color:#64748b;"><b style="color:#475569;">AI insight</b> {{.InsightNote}}</td></tr>
      {{end}}

      {{if .LogTail}}
      <tr><td style="padding:20px 28px 0;">
        <h2 style="margin:0 0 8px;font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#64748b;">Last {{len .LogTail}} log lines</h2>
        <div style="padding:14px 16px;background:#0f172a;border-radius:8px;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,'Liberation Mono',monospace;font-size:12px;line-height:1.6;color:#e2e8f0;white-space:pre-wrap;word-break:break-all;">{{range .LogTail}}{{.}}
{{end}}</div>
        <p style="margin:6px 0 0;font-size:12px;color:#64748b;">Secret values are masked. The full log is on the run page.</p>
      </td></tr>
      {{end}}

      <tr><td style="padding:24px 28px 0;font-size:0;line-height:0;">&nbsp;</td></tr>
    </table>
  </td></tr>

  <tr><td style="padding:16px 8px 0;font-size:12px;line-height:1.6;color:#64748b;">
    {{.Reason}}{{if .SettingsLink}} <a href="{{.SettingsLink}}" style="color:#0f766e;">Manage recipients and events</a>.{{end}}
    {{if .Link}}<br>Run link: <a href="{{.Link}}" style="color:#0f766e;word-break:break-all;">{{.Link}}</a>{{end}}
  </td></tr>
</table>
</td></tr>
</table>
</body>
</html>`))

// HTML renders the HTML body.
func (e Event) HTML() string {
	badge, color, soft := e.tone()
	label := e.LinkLabel
	if label == "" {
		label = "Open in Keel"
	}
	preheader := e.Summary
	if preheader == "" {
		preheader = e.Title
	}
	data := map[string]any{
		"Title": e.Title, "Summary": e.Summary, "OrgName": e.OrgName, "Preheader": preheader,
		"Badge": badge, "Color": color, "Soft": soft, "Error": e.Error,
		"Facts": e.Facts, "Inputs": e.Inputs, "LogTail": e.LogTail,
		"Link": e.Link, "LinkLabel": label, "SettingsLink": e.SettingsLink, "Reason": e.reason(),
		"Insight": template.HTML(""), "InsightNote": e.InsightNote,
	}
	if e.Insight != "" {
		data["Insight"] = renderMarkdown(e.Insight)
	}
	var buf bytes.Buffer
	if err := emailTmpl.Execute(&buf, data); err != nil {
		return "<pre>" + template.HTMLEscapeString(e.Text()) + "</pre>"
	}
	return buf.String()
}
