// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package devdb

import (
	"database/sql"
)

type Run struct {
	ID         string
	TargetID   sql.NullString
	Deployment string
	TargetName string
	Status     string
	ExitCode   sql.NullInt64
	FailedStep sql.NullInt64
	Error      string
	CreatedAt  int64
	StartedAt  sql.NullInt64
	FinishedAt sql.NullInt64
}

type RunInput struct {
	RunID      string
	Idx        int64
	Name       string
	Label      string
	ValueEnc   []byte
	IsSecret   int64
	DeployTime int64
	Source     string
}

type RunLog struct {
	RunID     string
	Seq       int64
	Line      string
	CreatedAt int64
}

type RunOutput struct {
	RunID     string
	Name      string
	ValueEnc  []byte
	IsSecret  int64
	CreatedAt int64
}

type RunStep struct {
	RunID  string
	Idx    int64
	Name   string
	Status string
}

type Target struct {
	ID          string
	Deployment  string
	Name        string
	Description string
	CreatedAt   int64
	UpdatedAt   int64
}

type TargetValue struct {
	TargetID  string
	VarName   string
	ValueEnc  []byte
	IsSecret  int64
	UpdatedAt int64
}
