// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package devdb

import (
	"context"
	"database/sql"
)

const appendRunLog = `-- name: AppendRunLog :exec

INSERT INTO run_logs (run_id, seq, line, created_at) VALUES (?, ?, ?, ?)
`

type AppendRunLogParams struct {
	RunID     string
	Seq       int64
	Line      string
	CreatedAt int64
}

// Run logs -------------------------------------------------------------------
func (q *Queries) AppendRunLog(ctx context.Context, arg AppendRunLogParams) error {
	_, err := q.db.ExecContext(ctx, appendRunLog,
		arg.RunID,
		arg.Seq,
		arg.Line,
		arg.CreatedAt,
	)
	return err
}

const createRun = `-- name: CreateRun :one

INSERT INTO runs (id, target_id, deployment, target_name, status, created_at)
VALUES (?, ?, ?, ?, 'queued', ?)
RETURNING id, target_id, deployment, target_name, status, exit_code, failed_step, error, created_at, started_at, finished_at
`

type CreateRunParams struct {
	ID         string
	TargetID   sql.NullString
	Deployment string
	TargetName string
	CreatedAt  int64
}

// Runs -----------------------------------------------------------------------
func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (*Run, error) {
	row := q.db.QueryRowContext(ctx, createRun,
		arg.ID,
		arg.TargetID,
		arg.Deployment,
		arg.TargetName,
		arg.CreatedAt,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.Deployment,
		&i.TargetName,
		&i.Status,
		&i.ExitCode,
		&i.FailedStep,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return &i, err
}

const createTarget = `-- name: CreateTarget :one

INSERT INTO targets (id, deployment, name, description, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, deployment, name, description, created_at, updated_at
`

type CreateTargetParams struct {
	ID          string
	Deployment  string
	Name        string
	Description string
	CreatedAt   int64
	UpdatedAt   int64
}

// Targets -------------------------------------------------------------------
func (q *Queries) CreateTarget(ctx context.Context, arg CreateTargetParams) (*Target, error) {
	row := q.db.QueryRowContext(ctx, createTarget,
		arg.ID,
		arg.Deployment,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Deployment,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteTarget = `-- name: DeleteTarget :exec
DELETE FROM targets WHERE id = ?
`

func (q *Queries) DeleteTarget(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTarget, id)
	return err
}

const deleteTargetValue = `-- name: DeleteTargetValue :exec
DELETE FROM target_values WHERE target_id = ? AND var_name = ?
`

type DeleteTargetValueParams struct {
	TargetID string
	VarName  string
}

func (q *Queries) DeleteTargetValue(ctx context.Context, arg DeleteTargetValueParams) error {
	_, err := q.db.ExecContext(ctx, deleteTargetValue, arg.TargetID, arg.VarName)
	return err
}

const finishRun = `-- name: FinishRun :exec
UPDATE runs SET status = ?, exit_code = ?, failed_step = ?, error = ?, finished_at = ?
WHERE id = ?
`

type FinishRunParams struct {
	Status     string
	ExitCode   sql.NullInt64
	FailedStep sql.NullInt64
	Error      string
	FinishedAt sql.NullInt64
	ID         string
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) error {
	_, err := q.db.ExecContext(ctx, finishRun,
		arg.Status,
		arg.ExitCode,
		arg.FailedStep,
		arg.Error,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const getRun = `-- name: GetRun :one
SELECT id, target_id, deployment, target_name, status, exit_code, failed_step, error, created_at, started_at, finished_at FROM runs WHERE id = ?
`

func (q *Queries) GetRun(ctx context.Context, id string) (*Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.Deployment,
		&i.TargetName,
		&i.Status,
		&i.ExitCode,
		&i.FailedStep,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return &i, err
}

const getTarget = `-- name: GetTarget :one
SELECT id, deployment, name, description, created_at, updated_at FROM targets WHERE id = ?
`

func (q *Queries) GetTarget(ctx context.Context, id string) (*Target, error) {
	row := q.db.QueryRowContext(ctx, getTarget, id)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Deployment,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTargetByName = `-- name: GetTargetByName :one
SELECT id, deployment, name, description, created_at, updated_at FROM targets WHERE deployment = ? AND name = ?
`

type GetTargetByNameParams struct {
	Deployment string
	Name       string
}

func (q *Queries) GetTargetByName(ctx context.Context, arg GetTargetByNameParams) (*Target, error) {
	row := q.db.QueryRowContext(ctx, getTargetByName, arg.Deployment, arg.Name)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Deployment,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertRunOutput = `-- name: InsertRunOutput :exec
INSERT INTO run_outputs (run_id, name, value_enc, is_secret, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (run_id, name) DO UPDATE SET value_enc = excluded.value_enc, is_secret = excluded.is_secret
`

type InsertRunOutputParams struct {
	RunID     string
	Name      string
	ValueEnc  []byte
	IsSecret  int64
	CreatedAt int64
}

func (q *Queries) InsertRunOutput(ctx context.Context, arg InsertRunOutputParams) error {
	_, err := q.db.ExecContext(ctx, insertRunOutput,
		arg.RunID,
		arg.Name,
		arg.ValueEnc,
		arg.IsSecret,
		arg.CreatedAt,
	)
	return err
}

const insertRunStep = `-- name: InsertRunStep :exec

INSERT INTO run_steps (run_id, idx, name, status) VALUES (?, ?, ?, 'pending')
`

type InsertRunStepParams struct {
	RunID string
	Idx   int64
	Name  string
}

// Run steps ------------------------------------------------------------------
func (q *Queries) InsertRunStep(ctx context.Context, arg InsertRunStepParams) error {
	_, err := q.db.ExecContext(ctx, insertRunStep, arg.RunID, arg.Idx, arg.Name)
	return err
}

const latestSucceededRunForTarget = `-- name: LatestSucceededRunForTarget :one
SELECT id, target_id, deployment, target_name, status, exit_code, failed_step, error, created_at, started_at, finished_at FROM runs WHERE target_id = ? AND status = 'succeeded'
ORDER BY created_at DESC, id DESC LIMIT 1
`

func (q *Queries) LatestSucceededRunForTarget(ctx context.Context, targetID sql.NullString) (*Run, error) {
	row := q.db.QueryRowContext(ctx, latestSucceededRunForTarget, targetID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.Deployment,
		&i.TargetName,
		&i.Status,
		&i.ExitCode,
		&i.FailedStep,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return &i, err
}

const listActiveRuns = `-- name: ListActiveRuns :many
SELECT id, target_id, deployment, target_name, status, exit_code, failed_step, error, created_at, started_at, finished_at FROM runs WHERE status IN ('queued', 'building', 'running')
ORDER BY created_at DESC
`

func (q *Queries) ListActiveRuns(ctx context.Context) ([]*Run, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.Deployment,
			&i.TargetName,
			&i.Status,
			&i.ExitCode,
			&i.FailedStep,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunLogs = `-- name: ListRunLogs :many
SELECT run_id, seq, line, created_at FROM run_logs WHERE run_id = ? ORDER BY seq
`

func (q *Queries) ListRunLogs(ctx context.Context, runID string) ([]*RunLog, error) {
	rows, err := q.db.QueryContext(ctx, listRunLogs, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RunLog
	for rows.Next() {
		var i RunLog
		if err := rows.Scan(
			&i.RunID,
			&i.Seq,
			&i.Line,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunLogsAfter = `-- name: ListRunLogsAfter :many
SELECT run_id, seq, line, created_at FROM run_logs WHERE run_id = ? AND seq > ? ORDER BY seq
`

type ListRunLogsAfterParams struct {
	RunID string
	Seq   int64
}

func (q *Queries) ListRunLogsAfter(ctx context.Context, arg ListRunLogsAfterParams) ([]*RunLog, error) {
	rows, err := q.db.QueryContext(ctx, listRunLogsAfter, arg.RunID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RunLog
	for rows.Next() {
		var i RunLog
		if err := rows.Scan(
			&i.RunID,
			&i.Seq,
			&i.Line,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunOutputs = `-- name: ListRunOutputs :many
SELECT run_id, name, value_enc, is_secret, created_at FROM run_outputs WHERE run_id = ? ORDER BY name
`

func (q *Queries) ListRunOutputs(ctx context.Context, runID string) ([]*RunOutput, error) {
	rows, err := q.db.QueryContext(ctx, listRunOutputs, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RunOutput
	for rows.Next() {
		var i RunOutput
		if err := rows.Scan(
			&i.RunID,
			&i.Name,
			&i.ValueEnc,
			&i.IsSecret,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunSteps = `-- name: ListRunSteps :many
SELECT run_id, idx, name, status FROM run_steps WHERE run_id = ? ORDER BY idx
`

func (q *Queries) ListRunSteps(ctx context.Context, runID string) ([]*RunStep, error) {
	rows, err := q.db.QueryContext(ctx, listRunSteps, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RunStep
	for rows.Next() {
		var i RunStep
		if err := rows.Scan(
			&i.RunID,
			&i.Idx,
			&i.Name,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, target_id, deployment, target_name, status, exit_code, failed_step, error, created_at, started_at, finished_at FROM runs ORDER BY created_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListRuns(ctx context.Context, limit int64) ([]*Run, error) {
	rows, err := q.db.QueryContext(ctx, listRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.Deployment,
			&i.TargetName,
			&i.Status,
			&i.ExitCode,
			&i.FailedStep,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByTarget = `-- name: ListRunsByTarget :many
SELECT id, target_id, deployment, target_name, status, exit_code, failed_step, error, created_at, started_at, finished_at FROM runs WHERE target_id = ? ORDER BY created_at DESC, id DESC LIMIT ?
`

type ListRunsByTargetParams struct {
	TargetID sql.NullString
	Limit    int64
}

func (q *Queries) ListRunsByTarget(ctx context.Context, arg ListRunsByTargetParams) ([]*Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByTarget, arg.TargetID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.Deployment,
			&i.TargetName,
			&i.Status,
			&i.ExitCode,
			&i.FailedStep,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetValues = `-- name: ListTargetValues :many
SELECT target_id, var_name, value_enc, is_secret, updated_at FROM target_values WHERE target_id = ? ORDER BY var_name
`

func (q *Queries) ListTargetValues(ctx context.Context, targetID string) ([]*TargetValue, error) {
	rows, err := q.db.QueryContext(ctx, listTargetValues, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TargetValue
	for rows.Next() {
		var i TargetValue
		if err := rows.Scan(
			&i.TargetID,
			&i.VarName,
			&i.ValueEnc,
			&i.IsSecret,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargets = `-- name: ListTargets :many
SELECT id, deployment, name, description, created_at, updated_at FROM targets ORDER BY deployment, name
`

func (q *Queries) ListTargets(ctx context.Context) ([]*Target, error) {
	rows, err := q.db.QueryContext(ctx, listTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.Deployment,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetsByDeployment = `-- name: ListTargetsByDeployment :many
SELECT id, deployment, name, description, created_at, updated_at FROM targets WHERE deployment = ? ORDER BY name
`

func (q *Queries) ListTargetsByDeployment(ctx context.Context, deployment string) ([]*Target, error) {
	rows, err := q.db.QueryContext(ctx, listTargetsByDeployment, deployment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.Deployment,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInterruptedRuns = `-- name: MarkInterruptedRuns :exec
UPDATE runs SET status = 'failed', error = 'interrupted: keel dev was stopped while the run was in progress', finished_at = ?
WHERE status IN ('queued', 'building', 'running')
`

func (q *Queries) MarkInterruptedRuns(ctx context.Context, finishedAt sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, markInterruptedRuns, finishedAt)
	return err
}

const setRunStatus = `-- name: SetRunStatus :exec
UPDATE runs SET status = ? WHERE id = ?
`

type SetRunStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) SetRunStatus(ctx context.Context, arg SetRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, setRunStatus, arg.Status, arg.ID)
	return err
}

const setRunStepStatus = `-- name: SetRunStepStatus :exec
UPDATE run_steps SET status = ? WHERE run_id = ? AND idx = ?
`

type SetRunStepStatusParams struct {
	Status string
	RunID  string
	Idx    int64
}

func (q *Queries) SetRunStepStatus(ctx context.Context, arg SetRunStepStatusParams) error {
	_, err := q.db.ExecContext(ctx, setRunStepStatus, arg.Status, arg.RunID, arg.Idx)
	return err
}

const skipUnfinishedRunSteps = `-- name: SkipUnfinishedRunSteps :exec
UPDATE run_steps SET status = 'skipped'
WHERE run_id = ? AND status IN ('pending', 'running')
`

func (q *Queries) SkipUnfinishedRunSteps(ctx context.Context, runID string) error {
	_, err := q.db.ExecContext(ctx, skipUnfinishedRunSteps, runID)
	return err
}

const startRun = `-- name: StartRun :exec
UPDATE runs SET status = ?, started_at = ? WHERE id = ?
`

type StartRunParams struct {
	Status    string
	StartedAt sql.NullInt64
	ID        string
}

func (q *Queries) StartRun(ctx context.Context, arg StartRunParams) error {
	_, err := q.db.ExecContext(ctx, startRun, arg.Status, arg.StartedAt, arg.ID)
	return err
}

const updateTarget = `-- name: UpdateTarget :one
UPDATE targets SET name = ?, description = ?, updated_at = ?
WHERE id = ?
RETURNING id, deployment, name, description, created_at, updated_at
`

type UpdateTargetParams struct {
	Name        string
	Description string
	UpdatedAt   int64
	ID          string
}

func (q *Queries) UpdateTarget(ctx context.Context, arg UpdateTargetParams) (*Target, error) {
	row := q.db.QueryRowContext(ctx, updateTarget,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Deployment,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertTargetValue = `-- name: UpsertTargetValue :exec

INSERT INTO target_values (target_id, var_name, value_enc, is_secret, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (target_id, var_name)
DO UPDATE SET value_enc = excluded.value_enc,
              is_secret = excluded.is_secret,
              updated_at = excluded.updated_at
`

type UpsertTargetValueParams struct {
	TargetID  string
	VarName   string
	ValueEnc  []byte
	IsSecret  int64
	UpdatedAt int64
}

// Target values --------------------------------------------------------------
func (q *Queries) UpsertTargetValue(ctx context.Context, arg UpsertTargetValueParams) error {
	_, err := q.db.ExecContext(ctx, upsertTargetValue,
		arg.TargetID,
		arg.VarName,
		arg.ValueEnc,
		arg.IsSecret,
		arg.UpdatedAt,
	)
	return err
}
