// Package manifest generates variable manifest documents.
//
// A manifest is the document you hand to whoever must supply the values a
// deployment needs — often a non-technical client or a third party. It lists
// each selected variable with its description, why it is needed, and how to
// obtain it, exactly as the configuration author specified in keel.yaml.
package manifest

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/smart-minds/keel/internal/config"
)

// Options control manifest generation.
type Options struct {
	// Select limits the manifest to these variable names. When nil, the
	// deployment's default selection is used (variables whose manifest block
	// sets include: true). When non-nil, it is used as-is.
	Select []string

	// ProjectName is shown in the document header (repository or project).
	ProjectName string

	// TargetName, when set, names the deployment target the values are for.
	TargetName string

	// PreparedBy optionally names who generated the document.
	PreparedBy string

	// Now is the generation timestamp; the zero value means time.Now().
	Now time.Time
}

// DefaultSelection returns the names of the variables included in a
// deployment's manifest by default.
func DefaultSelection(d *config.Deployment) []string {
	var names []string
	for _, v := range d.Variables {
		if v.Manifest.Include {
			names = append(names, v.Name)
		}
	}
	return names
}

// Generate renders the manifest for a deployment as a Markdown document.
// It returns an error if a selected variable does not exist or if the
// selection is empty.
func Generate(d *config.Deployment, opts Options) (string, error) {
	selected := opts.Select
	if selected == nil {
		selected = DefaultSelection(d)
	}
	if len(selected) == 0 {
		return "", fmt.Errorf("no variables selected for the manifest (mark variables with a `manifest:` block in keel.yaml, or select them explicitly)")
	}
	var vars []*config.Variable
	for _, name := range selected {
		v := d.Variable(name)
		if v == nil {
			return "", fmt.Errorf("variable %q is not declared in deployment %q", name, d.Name)
		}
		vars = append(vars, v)
	}

	now := opts.Now
	if now.IsZero() {
		now = time.Now()
	}

	var b strings.Builder
	title := "Required values"
	if opts.ProjectName != "" {
		title = fmt.Sprintf("Required values — %s", opts.ProjectName)
	}
	fmt.Fprintf(&b, "# %s\n\n", title)

	fmt.Fprintf(&b, "**Deployment:** `%s`", d.Name)
	if opts.TargetName != "" {
		fmt.Fprintf(&b, " &nbsp;·&nbsp; **Target:** `%s`", opts.TargetName)
	}
	fmt.Fprintf(&b, " &nbsp;·&nbsp; **Generated:** %s", now.Format("January 2, 2006"))
	if opts.PreparedBy != "" {
		fmt.Fprintf(&b, " &nbsp;·&nbsp; **Prepared by:** %s", opts.PreparedBy)
	}
	b.WriteString("\n\n")

	if strings.TrimSpace(d.Description) != "" {
		b.WriteString(strings.TrimSpace(d.Description))
		b.WriteString("\n\n")
	}

	fmt.Fprintf(&b, "The deployment needs the **%d value%s** listed below. "+
		"Each entry explains what the value is, why it is needed, and how to obtain it. "+
		"Values marked **sensitive** should be shared through a secure channel — never by plain email or chat.\n\n",
		len(vars), plural(len(vars)))

	// Summary table.
	b.WriteString("| # | Value | Type | Sensitive | Required |\n")
	b.WriteString("|---|-------|------|-----------|----------|\n")
	for i, v := range vars {
		fmt.Fprintf(&b, "| %d | %s | %s | %s | %s |\n",
			i+1, v.EffectiveLabel(), typeLabel(v), yesNo(v.Secret), yesNo(v.Required))
	}
	b.WriteString("\n---\n\n")

	for i, v := range vars {
		writeVariable(&b, i+1, v)
	}

	b.WriteString("---\n\n*Generated by [Keel](https://keel.dev) from this project's deployment configuration.*\n")
	return b.String(), nil
}

func writeVariable(b *strings.Builder, n int, v *config.Variable) {
	title := v.Manifest.Title
	if strings.TrimSpace(title) == "" {
		title = v.EffectiveLabel()
	}
	fmt.Fprintf(b, "## %d. %s\n\n", n, title)

	var meta []string
	meta = append(meta, fmt.Sprintf("Type: %s", typeLabel(v)))
	if v.Secret {
		meta = append(meta, "**Sensitive — share securely**")
	}
	if !v.Required {
		meta = append(meta, "Optional")
	}
	if v.Default != "" {
		meta = append(meta, fmt.Sprintf("Default: `%s`", v.Default))
	}
	if v.DeployTime {
		meta = append(meta, "Provided each time a deploy starts")
	}
	if v.When != nil {
		meta = append(meta, fmt.Sprintf("Only applies when %s", v.When.Describe()))
	}
	fmt.Fprintf(b, "%s\n\n", strings.Join(meta, " · "))

	if strings.TrimSpace(v.Description) != "" {
		fmt.Fprintf(b, "%s\n\n", strings.TrimSpace(v.Description))
	}
	if strings.TrimSpace(v.Manifest.Why) != "" {
		fmt.Fprintf(b, "**Why it is needed**\n\n%s\n\n", strings.TrimSpace(v.Manifest.Why))
	}
	if strings.TrimSpace(v.Manifest.How) != "" {
		fmt.Fprintf(b, "**How to get it**\n\n%s\n\n", strings.TrimSpace(v.Manifest.How))
	}
	if v.Type == config.VarSelect && len(v.Options) > 0 {
		b.WriteString("**Allowed values**\n\n")
		for _, o := range v.Options {
			if o.Label != "" && o.Label != o.Value {
				fmt.Fprintf(b, "- `%s` — %s\n", o.Value, o.Label)
			} else {
				fmt.Fprintf(b, "- `%s`\n", o.Value)
			}
		}
		b.WriteString("\n")
	}
	if c := constraintText(v); c != "" {
		fmt.Fprintf(b, "**Format**\n\n%s\n\n", c)
	}
}

// constraintText renders the validation constraints in plain language.
func constraintText(v *config.Variable) string {
	var parts []string
	val := v.Validation
	if val.Min != nil && val.Max != nil {
		parts = append(parts, fmt.Sprintf("A number between %v and %v.", trimNum(*val.Min), trimNum(*val.Max)))
	} else if val.Min != nil {
		parts = append(parts, fmt.Sprintf("A number of at least %v.", trimNum(*val.Min)))
	} else if val.Max != nil {
		parts = append(parts, fmt.Sprintf("A number of at most %v.", trimNum(*val.Max)))
	}
	if val.MinLength != nil && val.MaxLength != nil {
		parts = append(parts, fmt.Sprintf("Between %d and %d characters.", *val.MinLength, *val.MaxLength))
	} else if val.MinLength != nil {
		parts = append(parts, fmt.Sprintf("At least %d characters.", *val.MinLength))
	} else if val.MaxLength != nil {
		parts = append(parts, fmt.Sprintf("At most %d characters.", *val.MaxLength))
	}
	if val.Pattern != "" {
		if val.Message != "" {
			parts = append(parts, val.Message+".")
		} else {
			parts = append(parts, fmt.Sprintf("Must match the pattern `%s`.", val.Pattern))
		}
	}
	return strings.Join(parts, " ")
}

func typeLabel(v *config.Variable) string {
	switch v.Type {
	case config.VarText:
		return "Text"
	case config.VarMultiline:
		return "Multi-line text"
	case config.VarNumber:
		return "Number"
	case config.VarEmail:
		return "Email address"
	case config.VarURL:
		return "URL"
	case config.VarBoolean:
		return "Yes / no"
	case config.VarSelect:
		return "One of a list"
	}
	return string(v.Type)
}

func trimNum(f float64) string {
	return strings.TrimRight(strings.TrimRight(fmt.Sprintf("%f", f), "0"), ".")
}

func yesNo(b bool) string {
	if b {
		return "Yes"
	}
	return "No"
}

func plural(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}

// SortSelection orders names by their position in the deployment's variable
// list, so manifests always follow document order regardless of how the
// selection was assembled.
func SortSelection(d *config.Deployment, names []string) []string {
	pos := make(map[string]int, len(d.Variables))
	for i, v := range d.Variables {
		pos[v.Name] = i
	}
	out := append([]string(nil), names...)
	sort.SliceStable(out, func(i, j int) bool { return pos[out[i]] < pos[out[j]] })
	return out
}
