// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package clouddb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type GithubInstallation struct {
	InstallationID int64
	AccountLogin   string
	AccountType    string
	CreatedAt      time.Time
}

type NotificationDelivery struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	Event      string
	Subject    string
	Recipients []string
	Status     string
	Error      string
	CreatedAt  time.Time
}

type NotificationRecipient struct {
	ID             uuid.UUID
	OrgID          uuid.UUID
	Email          string
	Events         []string
	Enabled        bool
	CreatedBy      uuid.NullUUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	IncludeInsight bool
}

type Org struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	Personal  bool
	CreatedBy uuid.NullUUID
	CreatedAt time.Time
}

type OrgAiSetting struct {
	OrgID      uuid.UUID
	BaseUrl    string
	ApiKeyEnc  []byte
	Model      string
	VerifiedAt *time.Time
	UpdatedBy  uuid.NullUUID
	UpdatedAt  time.Time
}

type OrgInvite struct {
	ID           uuid.UUID
	OrgID        uuid.UUID
	Email        string
	Role         string
	CanConfigure bool
	CanDeploy    bool
	TokenHash    []byte
	InvitedBy    uuid.NullUUID
	CreatedAt    time.Time
	ExpiresAt    time.Time
	AcceptedAt   *time.Time
}

type OrgMember struct {
	OrgID        uuid.UUID
	UserID       uuid.UUID
	Role         string
	CanConfigure bool
	CanDeploy    bool
	CreatedAt    time.Time
}

type OrgSmtpSetting struct {
	OrgID         uuid.UUID
	Host          string
	Port          int32
	Username      string
	PasswordEnc   []byte
	Encryption    string
	FromAddress   string
	FromName      string
	LastTestAt    *time.Time
	LastTestError string
	UpdatedBy     uuid.NullUUID
	UpdatedAt     time.Time
}

type Repo struct {
	ID                   uuid.UUID
	OrgID                uuid.UUID
	Name                 string
	Provider             string
	GitUrl               string
	Branch               string
	AuthTokenEnc         []byte
	GithubInstallationID pgtype.Int8
	GithubFullName       string
	Status               string
	ConfigYaml           string
	ConfigError          string
	LastCommitSha        string
	LastSyncedAt         *time.Time
	CreatedBy            uuid.NullUUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Run struct {
	ID          uuid.UUID
	RepoID      uuid.UUID
	TargetID    uuid.NullUUID
	Deployment  string
	TargetName  string
	Status      string
	TriggerKind string
	CommitSha   string
	ExitCode    pgtype.Int4
	FailedStep  pgtype.Int4
	Error       string
	StartedBy   uuid.NullUUID
	CreatedAt   time.Time
	StartedAt   *time.Time
	FinishedAt  *time.Time
}

type RunInput struct {
	RunID      uuid.UUID
	Idx        int32
	Name       string
	Label      string
	ValueEnc   []byte
	IsSecret   bool
	DeployTime bool
	Source     string
}

type RunInsight struct {
	RunID     uuid.UUID
	Model     string
	Content   string
	CreatedBy uuid.NullUUID
	CreatedAt time.Time
}

type RunLog struct {
	RunID     uuid.UUID
	Seq       int32
	Line      string
	CreatedAt time.Time
}

type RunOutput struct {
	RunID     uuid.UUID
	Name      string
	ValueEnc  []byte
	IsSecret  bool
	CreatedAt time.Time
}

type RunStep struct {
	RunID  uuid.UUID
	Idx    int32
	Name   string
	Status string
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	CsrfToken string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Target struct {
	ID          uuid.UUID
	RepoID      uuid.UUID
	Deployment  string
	Name        string
	Description string
	AutoDeploy  bool
	CreatedBy   uuid.NullUUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type TargetValue struct {
	TargetID  uuid.UUID
	VarName   string
	ValueEnc  []byte
	IsSecret  bool
	UpdatedBy uuid.NullUUID
	UpdatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
