// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package clouddb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvite = `-- name: AcceptInvite :exec
UPDATE org_invites SET accepted_at = now() WHERE id = $1
`

func (q *Queries) AcceptInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, acceptInvite, id)
	return err
}

const appendRunLog = `-- name: AppendRunLog :exec

INSERT INTO run_logs (run_id, seq, line) VALUES ($1, $2, $3)
`

type AppendRunLogParams struct {
	RunID uuid.UUID
	Seq   int32
	Line  string
}

// Run logs -------------------------------------------------------------------
func (q *Queries) AppendRunLog(ctx context.Context, arg AppendRunLogParams) error {
	_, err := q.db.Exec(ctx, appendRunLog, arg.RunID, arg.Seq, arg.Line)
	return err
}

const countActiveRunsForTarget = `-- name: CountActiveRunsForTarget :one
SELECT count(*) FROM runs
WHERE target_id = $1 AND status IN ('queued', 'building', 'running')
`

func (q *Queries) CountActiveRunsForTarget(ctx context.Context, targetID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRunsForTarget, targetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrgOwners = `-- name: CountOrgOwners :one
SELECT count(*) FROM org_members WHERE org_id = $1 AND role = 'owner'
`

func (q *Queries) CountOrgOwners(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrgOwners, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvite = `-- name: CreateInvite :one

INSERT INTO org_invites (org_id, email, role, can_configure, can_deploy, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, email, role, can_configure, can_deploy, token_hash, invited_by, created_at, expires_at, accepted_at
`

type CreateInviteParams struct {
	OrgID        uuid.UUID
	Email        string
	Role         string
	CanConfigure bool
	CanDeploy    bool
	TokenHash    []byte
	InvitedBy    uuid.NullUUID
	ExpiresAt    time.Time
}

// Org invites ----------------------------------------------------------------
func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (*OrgInvite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.OrgID,
		arg.Email,
		arg.Role,
		arg.CanConfigure,
		arg.CanDeploy,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i OrgInvite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.CanConfigure,
		&i.CanDeploy,
		&i.TokenHash,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
	)
	return &i, err
}

const createOrg = `-- name: CreateOrg :one

INSERT INTO orgs (slug, name, personal, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, name, personal, created_by, created_at
`

type CreateOrgParams struct {
	Slug      string
	Name      string
	Personal  bool
	CreatedBy uuid.NullUUID
}

// Orgs -----------------------------------------------------------------------
func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (*Org, error) {
	row := q.db.QueryRow(ctx, createOrg,
		arg.Slug,
		arg.Name,
		arg.Personal,
		arg.CreatedBy,
	)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Personal,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const createOrgMember = `-- name: CreateOrgMember :one

INSERT INTO org_members (org_id, user_id, role, can_configure, can_deploy)
VALUES ($1, $2, $3, $4, $5)
RETURNING org_id, user_id, role, can_configure, can_deploy, created_at
`

type CreateOrgMemberParams struct {
	OrgID        uuid.UUID
	UserID       uuid.UUID
	Role         string
	CanConfigure bool
	CanDeploy    bool
}

// Org members ----------------------------------------------------------------
func (q *Queries) CreateOrgMember(ctx context.Context, arg CreateOrgMemberParams) (*OrgMember, error) {
	row := q.db.QueryRow(ctx, createOrgMember,
		arg.OrgID,
		arg.UserID,
		arg.Role,
		arg.CanConfigure,
		arg.CanDeploy,
	)
	var i OrgMember
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CanConfigure,
		&i.CanDeploy,
		&i.CreatedAt,
	)
	return &i, err
}

const createRecipient = `-- name: CreateRecipient :one

INSERT INTO notification_recipients (org_id, email, events, enabled, include_insight, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, email, events, enabled, created_by, created_at, updated_at, include_insight
`

type CreateRecipientParams struct {
	OrgID          uuid.UUID
	Email          string
	Events         []string
	Enabled        bool
	IncludeInsight bool
	CreatedBy      uuid.NullUUID
}

// Notification recipients ----------------------------------------------------
func (q *Queries) CreateRecipient(ctx context.Context, arg CreateRecipientParams) (*NotificationRecipient, error) {
	row := q.db.QueryRow(ctx, createRecipient,
		arg.OrgID,
		arg.Email,
		arg.Events,
		arg.Enabled,
		arg.IncludeInsight,
		arg.CreatedBy,
	)
	var i NotificationRecipient
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Events,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IncludeInsight,
	)
	return &i, err
}

const createRepo = `-- name: CreateRepo :one

INSERT INTO repos (org_id, name, provider, git_url, branch, auth_token_enc, github_installation_id, github_full_name, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, name, provider, git_url, branch, auth_token_enc, github_installation_id, github_full_name, status, config_yaml, config_error, last_commit_sha, last_synced_at, created_by, created_at, updated_at
`

type CreateRepoParams struct {
	OrgID                uuid.UUID
	Name                 string
	Provider             string
	GitUrl               string
	Branch               string
	AuthTokenEnc         []byte
	GithubInstallationID pgtype.Int8
	GithubFullName       string
	CreatedBy            uuid.NullUUID
}

// Repos ----------------------------------------------------------------------
func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (*Repo, error) {
	row := q.db.QueryRow(ctx, createRepo,
		arg.OrgID,
		arg.Name,
		arg.Provider,
		arg.GitUrl,
		arg.Branch,
		arg.AuthTokenEnc,
		arg.GithubInstallationID,
		arg.GithubFullName,
		arg.CreatedBy,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Provider,
		&i.GitUrl,
		&i.Branch,
		&i.AuthTokenEnc,
		&i.GithubInstallationID,
		&i.GithubFullName,
		&i.Status,
		&i.ConfigYaml,
		&i.ConfigError,
		&i.LastCommitSha,
		&i.LastSyncedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createRun = `-- name: CreateRun :one

INSERT INTO runs (repo_id, target_id, deployment, target_name, trigger_kind, commit_sha, started_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, repo_id, target_id, deployment, target_name, status, trigger_kind, commit_sha, exit_code, failed_step, error, started_by, created_at, started_at, finished_at
`

type CreateRunParams struct {
	RepoID      uuid.UUID
	TargetID    uuid.NullUUID
	Deployment  string
	TargetName  string
	TriggerKind string
	CommitSha   string
	StartedBy   uuid.NullUUID
}

// Runs -----------------------------------------------------------------------
func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (*Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.RepoID,
		arg.TargetID,
		arg.Deployment,
		arg.TargetName,
		arg.TriggerKind,
		arg.CommitSha,
		arg.StartedBy,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TargetID,
		&i.Deployment,
		&i.TargetName,
		&i.Status,
		&i.TriggerKind,
		&i.CommitSha,
		&i.ExitCode,
		&i.FailedStep,
		&i.Error,
		&i.StartedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return &i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (user_id, token_hash, csrf_token, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, csrf_token, created_at, expires_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID
	TokenHash []byte
	CsrfToken string
	ExpiresAt time.Time
}

// Sessions -------------------------------------------------------------------
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (*Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.CsrfToken,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const createTarget = `-- name: CreateTarget :one

INSERT INTO targets (repo_id, deployment, name, description, auto_deploy, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, repo_id, deployment, name, description, auto_deploy, created_by, created_at, updated_at
`

type CreateTargetParams struct {
	RepoID      uuid.UUID
	Deployment  string
	Name        string
	Description string
	AutoDeploy  bool
	CreatedBy   uuid.NullUUID
}

// Targets --------------------------------------------------------------------
func (q *Queries) CreateTarget(ctx context.Context, arg CreateTargetParams) (*Target, error) {
	row := q.db.QueryRow(ctx, createTarget,
		arg.RepoID,
		arg.Deployment,
		arg.Name,
		arg.Description,
		arg.AutoDeploy,
		arg.CreatedBy,
	)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Deployment,
		&i.Name,
		&i.Description,
		&i.AutoDeploy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, name, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, name, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	Name         string
	PasswordHash string
}

// Users ----------------------------------------------------------------------
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteGithubInstallation = `-- name: DeleteGithubInstallation :exec
DELETE FROM github_installations WHERE installation_id = $1
`

func (q *Queries) DeleteGithubInstallation(ctx context.Context, installationID int64) error {
	_, err := q.db.Exec(ctx, deleteGithubInstallation, installationID)
	return err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM org_invites WHERE id = $1 AND org_id = $2
`

type DeleteInviteParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteInvite(ctx context.Context, arg DeleteInviteParams) error {
	_, err := q.db.Exec(ctx, deleteInvite, arg.ID, arg.OrgID)
	return err
}

const deleteOrg = `-- name: DeleteOrg :exec
DELETE FROM orgs WHERE id = $1
`

func (q *Queries) DeleteOrg(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrg, id)
	return err
}

const deleteOrgAI = `-- name: DeleteOrgAI :exec
DELETE FROM org_ai_settings WHERE org_id = $1
`

func (q *Queries) DeleteOrgAI(ctx context.Context, orgID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrgAI, orgID)
	return err
}

const deleteOrgMember = `-- name: DeleteOrgMember :exec
DELETE FROM org_members WHERE org_id = $1 AND user_id = $2
`

type DeleteOrgMemberParams struct {
	OrgID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteOrgMember(ctx context.Context, arg DeleteOrgMemberParams) error {
	_, err := q.db.Exec(ctx, deleteOrgMember, arg.OrgID, arg.UserID)
	return err
}

const deleteOrgSMTP = `-- name: DeleteOrgSMTP :exec
DELETE FROM org_smtp_settings WHERE org_id = $1
`

func (q *Queries) DeleteOrgSMTP(ctx context.Context, orgID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrgSMTP, orgID)
	return err
}

const deleteRecipient = `-- name: DeleteRecipient :exec
DELETE FROM notification_recipients WHERE id = $1 AND org_id = $2
`

type DeleteRecipientParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteRecipient(ctx context.Context, arg DeleteRecipientParams) error {
	_, err := q.db.Exec(ctx, deleteRecipient, arg.ID, arg.OrgID)
	return err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repos WHERE id = $1
`

func (q *Queries) DeleteRepo(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRepo, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteTarget = `-- name: DeleteTarget :exec
DELETE FROM targets WHERE id = $1
`

func (q *Queries) DeleteTarget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTarget, id)
	return err
}

const deleteTargetValue = `-- name: DeleteTargetValue :exec
DELETE FROM target_values WHERE target_id = $1 AND var_name = $2
`

type DeleteTargetValueParams struct {
	TargetID uuid.UUID
	VarName  string
}

func (q *Queries) DeleteTargetValue(ctx context.Context, arg DeleteTargetValueParams) error {
	_, err := q.db.Exec(ctx, deleteTargetValue, arg.TargetID, arg.VarName)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const finishRun = `-- name: FinishRun :exec
UPDATE runs SET status = $2, exit_code = $3, failed_step = $4, error = $5, finished_at = now()
WHERE id = $1
`

type FinishRunParams struct {
	ID         uuid.UUID
	Status     string
	ExitCode   pgtype.Int4
	FailedStep pgtype.Int4
	Error      string
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) error {
	_, err := q.db.Exec(ctx, finishRun,
		arg.ID,
		arg.Status,
		arg.ExitCode,
		arg.FailedStep,
		arg.Error,
	)
	return err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT id, org_id, email, role, can_configure, can_deploy, token_hash, invited_by, created_at, expires_at, accepted_at FROM org_invites
WHERE token_hash = $1 AND accepted_at IS NULL AND expires_at > now()
`

func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash []byte) (*OrgInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i OrgInvite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.CanConfigure,
		&i.CanDeploy,
		&i.TokenHash,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
	)
	return &i, err
}

const getOrg = `-- name: GetOrg :one
SELECT id, slug, name, personal, created_by, created_at FROM orgs WHERE id = $1
`

func (q *Queries) GetOrg(ctx context.Context, id uuid.UUID) (*Org, error) {
	row := q.db.QueryRow(ctx, getOrg, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Personal,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const getOrgAI = `-- name: GetOrgAI :one

SELECT org_id, base_url, api_key_enc, model, verified_at, updated_by, updated_at FROM org_ai_settings WHERE org_id = $1
`

// AI settings and insights ---------------------------------------------------
func (q *Queries) GetOrgAI(ctx context.Context, orgID uuid.UUID) (*OrgAiSetting, error) {
	row := q.db.QueryRow(ctx, getOrgAI, orgID)
	var i OrgAiSetting
	err := row.Scan(
		&i.OrgID,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.Model,
		&i.VerifiedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return &i, err
}

const getOrgBySlug = `-- name: GetOrgBySlug :one
SELECT id, slug, name, personal, created_by, created_at FROM orgs WHERE lower(slug) = lower($1)
`

func (q *Queries) GetOrgBySlug(ctx context.Context, lower string) (*Org, error) {
	row := q.db.QueryRow(ctx, getOrgBySlug, lower)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Personal,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const getOrgMember = `-- name: GetOrgMember :one
SELECT org_id, user_id, role, can_configure, can_deploy, created_at FROM org_members WHERE org_id = $1 AND user_id = $2
`

type GetOrgMemberParams struct {
	OrgID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (*OrgMember, error) {
	row := q.db.QueryRow(ctx, getOrgMember, arg.OrgID, arg.UserID)
	var i OrgMember
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CanConfigure,
		&i.CanDeploy,
		&i.CreatedAt,
	)
	return &i, err
}

const getOrgSMTP = `-- name: GetOrgSMTP :one

SELECT org_id, host, port, username, password_enc, encryption, from_address, from_name, last_test_at, last_test_error, updated_by, updated_at FROM org_smtp_settings WHERE org_id = $1
`

// SMTP settings --------------------------------------------------------------
func (q *Queries) GetOrgSMTP(ctx context.Context, orgID uuid.UUID) (*OrgSmtpSetting, error) {
	row := q.db.QueryRow(ctx, getOrgSMTP, orgID)
	var i OrgSmtpSetting
	err := row.Scan(
		&i.OrgID,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEnc,
		&i.Encryption,
		&i.FromAddress,
		&i.FromName,
		&i.LastTestAt,
		&i.LastTestError,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRecipient = `-- name: GetRecipient :one
SELECT id, org_id, email, events, enabled, created_by, created_at, updated_at, include_insight FROM notification_recipients WHERE id = $1 AND org_id = $2
`

type GetRecipientParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetRecipient(ctx context.Context, arg GetRecipientParams) (*NotificationRecipient, error) {
	row := q.db.QueryRow(ctx, getRecipient, arg.ID, arg.OrgID)
	var i NotificationRecipient
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Events,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IncludeInsight,
	)
	return &i, err
}

const getRepo = `-- name: GetRepo :one
SELECT id, org_id, name, provider, git_url, branch, auth_token_enc, github_installation_id, github_full_name, status, config_yaml, config_error, last_commit_sha, last_synced_at, created_by, created_at, updated_at FROM repos WHERE id = $1
`

func (q *Queries) GetRepo(ctx context.Context, id uuid.UUID) (*Repo, error) {
	row := q.db.QueryRow(ctx, getRepo, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Provider,
		&i.GitUrl,
		&i.Branch,
		&i.AuthTokenEnc,
		&i.GithubInstallationID,
		&i.GithubFullName,
		&i.Status,
		&i.ConfigYaml,
		&i.ConfigError,
		&i.LastCommitSha,
		&i.LastSyncedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRepoByName = `-- name: GetRepoByName :one
SELECT id, org_id, name, provider, git_url, branch, auth_token_enc, github_installation_id, github_full_name, status, config_yaml, config_error, last_commit_sha, last_synced_at, created_by, created_at, updated_at FROM repos WHERE org_id = $1 AND lower(name) = lower($2)
`

type GetRepoByNameParams struct {
	OrgID uuid.UUID
	Lower string
}

func (q *Queries) GetRepoByName(ctx context.Context, arg GetRepoByNameParams) (*Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByName, arg.OrgID, arg.Lower)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Provider,
		&i.GitUrl,
		&i.Branch,
		&i.AuthTokenEnc,
		&i.GithubInstallationID,
		&i.GithubFullName,
		&i.Status,
		&i.ConfigYaml,
		&i.ConfigError,
		&i.LastCommitSha,
		&i.LastSyncedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRepoInOrg = `-- name: GetRepoInOrg :one
SELECT id, org_id, name, provider, git_url, branch, auth_token_enc, github_installation_id, github_full_name, status, config_yaml, config_error, last_commit_sha, last_synced_at, created_by, created_at, updated_at FROM repos WHERE org_id = $1 AND id = $2
`

type GetRepoInOrgParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) GetRepoInOrg(ctx context.Context, arg GetRepoInOrgParams) (*Repo, error) {
	row := q.db.QueryRow(ctx, getRepoInOrg, arg.OrgID, arg.ID)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Provider,
		&i.GitUrl,
		&i.Branch,
		&i.AuthTokenEnc,
		&i.GithubInstallationID,
		&i.GithubFullName,
		&i.Status,
		&i.ConfigYaml,
		&i.ConfigError,
		&i.LastCommitSha,
		&i.LastSyncedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRun = `-- name: GetRun :one
SELECT id, repo_id, target_id, deployment, target_name, status, trigger_kind, commit_sha, exit_code, failed_step, error, started_by, created_at, started_at, finished_at FROM runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id uuid.UUID) (*Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TargetID,
		&i.Deployment,
		&i.TargetName,
		&i.Status,
		&i.TriggerKind,
		&i.CommitSha,
		&i.ExitCode,
		&i.FailedStep,
		&i.Error,
		&i.StartedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return &i, err
}

const getRunInsight = `-- name: GetRunInsight :one
SELECT run_id, model, content, created_by, created_at FROM run_insights WHERE run_id = $1
`

func (q *Queries) GetRunInsight(ctx context.Context, runID uuid.UUID) (*RunInsight, error) {
	row := q.db.QueryRow(ctx, getRunInsight, runID)
	var i RunInsight
	err := row.Scan(
		&i.RunID,
		&i.Model,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, csrf_token, created_at, expires_at FROM sessions WHERE token_hash = $1 AND expires_at > now()
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (*Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const getTarget = `-- name: GetTarget :one
SELECT id, repo_id, deployment, name, description, auto_deploy, created_by, created_at, updated_at FROM targets WHERE id = $1
`

func (q *Queries) GetTarget(ctx context.Context, id uuid.UUID) (*Target, error) {
	row := q.db.QueryRow(ctx, getTarget, id)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Deployment,
		&i.Name,
		&i.Description,
		&i.AutoDeploy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTargetByName = `-- name: GetTargetByName :one
SELECT id, repo_id, deployment, name, description, auto_deploy, created_by, created_at, updated_at FROM targets
WHERE repo_id = $1 AND deployment = $2 AND lower(name) = lower($3)
`

type GetTargetByNameParams struct {
	RepoID     uuid.UUID
	Deployment string
	Lower      string
}

func (q *Queries) GetTargetByName(ctx context.Context, arg GetTargetByNameParams) (*Target, error) {
	row := q.db.QueryRow(ctx, getTargetByName, arg.RepoID, arg.Deployment, arg.Lower)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Deployment,
		&i.Name,
		&i.Description,
		&i.AutoDeploy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, password_hash, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (*User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, created_at, updated_at FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertDelivery = `-- name: InsertDelivery :exec

INSERT INTO notification_deliveries (org_id, event, subject, recipients, status, error)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertDeliveryParams struct {
	OrgID      uuid.UUID
	Event      string
	Subject    string
	Recipients []string
	Status     string
	Error      string
}

// Notification deliveries ----------------------------------------------------
func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertDelivery,
		arg.OrgID,
		arg.Event,
		arg.Subject,
		arg.Recipients,
		arg.Status,
		arg.Error,
	)
	return err
}

const insertRunInput = `-- name: InsertRunInput :exec

INSERT INTO run_inputs (run_id, idx, name, label, value_enc, is_secret, deploy_time, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertRunInputParams struct {
	RunID      uuid.UUID
	Idx        int32
	Name       string
	Label      string
	ValueEnc   []byte
	IsSecret   bool
	DeployTime bool
	Source     string
}

// Run inputs -----------------------------------------------------------------
func (q *Queries) InsertRunInput(ctx context.Context, arg InsertRunInputParams) error {
	_, err := q.db.Exec(ctx, insertRunInput,
		arg.RunID,
		arg.Idx,
		arg.Name,
		arg.Label,
		arg.ValueEnc,
		arg.IsSecret,
		arg.DeployTime,
		arg.Source,
	)
	return err
}

const insertRunOutput = `-- name: InsertRunOutput :exec
INSERT INTO run_outputs (run_id, name, value_enc, is_secret)
VALUES ($1, $2, $3, $4)
ON CONFLICT (run_id, name) DO UPDATE SET value_enc = EXCLUDED.value_enc, is_secret = EXCLUDED.is_secret
`

type InsertRunOutputParams struct {
	RunID    uuid.UUID
	Name     string
	ValueEnc []byte
	IsSecret bool
}

func (q *Queries) InsertRunOutput(ctx context.Context, arg InsertRunOutputParams) error {
	_, err := q.db.Exec(ctx, insertRunOutput,
		arg.RunID,
		arg.Name,
		arg.ValueEnc,
		arg.IsSecret,
	)
	return err
}

const insertRunStep = `-- name: InsertRunStep :exec

INSERT INTO run_steps (run_id, idx, name, status) VALUES ($1, $2, $3, 'pending')
`

type InsertRunStepParams struct {
	RunID uuid.UUID
	Idx   int32
	Name  string
}

// Run steps ------------------------------------------------------------------
func (q *Queries) InsertRunStep(ctx context.Context, arg InsertRunStepParams) error {
	_, err := q.db.Exec(ctx, insertRunStep, arg.RunID, arg.Idx, arg.Name)
	return err
}

const latestSucceededRunForTarget = `-- name: LatestSucceededRunForTarget :one
SELECT id, repo_id, target_id, deployment, target_name, status, trigger_kind, commit_sha, exit_code, failed_step, error, started_by, created_at, started_at, finished_at FROM runs WHERE target_id = $1 AND status = 'succeeded'
ORDER BY created_at DESC, id DESC LIMIT 1
`

func (q *Queries) LatestSucceededRunForTarget(ctx context.Context, targetID uuid.NullUUID) (*Run, error) {
	row := q.db.QueryRow(ctx, latestSucceededRunForTarget, targetID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TargetID,
		&i.Deployment,
		&i.TargetName,
		&i.Status,
		&i.TriggerKind,
		&i.CommitSha,
		&i.ExitCode,
		&i.FailedStep,
		&i.Error,
		&i.StartedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return &i, err
}

const listAutoDeployTargets = `-- name: ListAutoDeployTargets :many
SELECT id, repo_id, deployment, name, description, auto_deploy, created_by, created_at, updated_at FROM targets WHERE repo_id = $1 AND auto_deploy = true ORDER BY deployment, name
`

func (q *Queries) ListAutoDeployTargets(ctx context.Context, repoID uuid.UUID) ([]*Target, error) {
	rows, err := q.db.Query(ctx, listAutoDeployTargets, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Deployment,
			&i.Name,
			&i.Description,
			&i.AutoDeploy,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT id, org_id, event, subject, recipients, status, error, created_at FROM notification_deliveries WHERE org_id = $1 ORDER BY created_at DESC, id DESC LIMIT $2
`

type ListDeliveriesParams struct {
	OrgID uuid.UUID
	Limit int32
}

func (q *Queries) ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]*NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, listDeliveries, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*NotificationDelivery
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Event,
			&i.Subject,
			&i.Recipients,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGithubInstallations = `-- name: ListGithubInstallations :many
SELECT installation_id, account_login, account_type, created_at FROM github_installations ORDER BY account_login
`

func (q *Queries) ListGithubInstallations(ctx context.Context) ([]*GithubInstallation, error) {
	rows, err := q.db.Query(ctx, listGithubInstallations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GithubInstallation
	for rows.Next() {
		var i GithubInstallation
		if err := rows.Scan(
			&i.InstallationID,
			&i.AccountLogin,
			&i.AccountType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgInvites = `-- name: ListOrgInvites :many
SELECT id, org_id, email, role, can_configure, can_deploy, token_hash, invited_by, created_at, expires_at, accepted_at FROM org_invites
WHERE org_id = $1 AND accepted_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) ListOrgInvites(ctx context.Context, orgID uuid.UUID) ([]*OrgInvite, error) {
	rows, err := q.db.Query(ctx, listOrgInvites, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*OrgInvite
	for rows.Next() {
		var i OrgInvite
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.Role,
			&i.CanConfigure,
			&i.CanDeploy,
			&i.TokenHash,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT m.org_id, m.user_id, m.role, m.can_configure, m.can_deploy, m.created_at, u.email, u.name
FROM org_members m
JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1
ORDER BY CASE m.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END, u.name
`

type ListOrgMembersRow struct {
	OrgID        uuid.UUID
	UserID       uuid.UUID
	Role         string
	CanConfigure bool
	CanDeploy    bool
	CreatedAt    time.Time
	Email        string
	Name         string
}

func (q *Queries) ListOrgMembers(ctx context.Context, orgID uuid.UUID) ([]*ListOrgMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrgMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListOrgMembersRow
	for rows.Next() {
		var i ListOrgMembersRow
		if err := rows.Scan(
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.CanConfigure,
			&i.CanDeploy,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsForUser = `-- name: ListOrgsForUser :many
SELECT o.id, o.slug, o.name, o.personal, o.created_by, o.created_at, m.role
FROM orgs o
JOIN org_members m ON m.org_id = o.id
WHERE m.user_id = $1
ORDER BY o.personal DESC, o.name
`

type ListOrgsForUserRow struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	Personal  bool
	CreatedBy uuid.NullUUID
	CreatedAt time.Time
	Role      string
}

func (q *Queries) ListOrgsForUser(ctx context.Context, userID uuid.UUID) ([]*ListOrgsForUserRow, error) {
	rows, err := q.db.Query(ctx, listOrgsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListOrgsForUserRow
	for rows.Next() {
		var i ListOrgsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Personal,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipients = `-- name: ListRecipients :many
SELECT id, org_id, email, events, enabled, created_by, created_at, updated_at, include_insight FROM notification_recipients WHERE org_id = $1 ORDER BY lower(email)
`

func (q *Queries) ListRecipients(ctx context.Context, orgID uuid.UUID) ([]*NotificationRecipient, error) {
	rows, err := q.db.Query(ctx, listRecipients, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*NotificationRecipient
	for rows.Next() {
		var i NotificationRecipient
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.Events,
			&i.Enabled,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IncludeInsight,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipientsForEvent = `-- name: ListRecipientsForEvent :many
SELECT id, org_id, email, events, enabled, created_by, created_at, updated_at, include_insight FROM notification_recipients
WHERE org_id = $1 AND enabled = true AND $2::text = ANY(events)
ORDER BY lower(email)
`

type ListRecipientsForEventParams struct {
	OrgID   uuid.UUID
	Column2 string
}

func (q *Queries) ListRecipientsForEvent(ctx context.Context, arg ListRecipientsForEventParams) ([]*NotificationRecipient, error) {
	rows, err := q.db.Query(ctx, listRecipientsForEvent, arg.OrgID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*NotificationRecipient
	for rows.Next() {
		var i NotificationRecipient
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.Events,
			&i.Enabled,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IncludeInsight,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposByGithubRepo = `-- name: ListReposByGithubRepo :many
SELECT id, org_id, name, provider, git_url, branch, auth_token_enc, github_installation_id, github_full_name, status, config_yaml, config_error, last_commit_sha, last_synced_at, created_by, created_at, updated_at FROM repos
WHERE github_installation_id = $1 AND lower(github_full_name) = lower($2)
`

type ListReposByGithubRepoParams struct {
	GithubInstallationID pgtype.Int8
	Lower                string
}

func (q *Queries) ListReposByGithubRepo(ctx context.Context, arg ListReposByGithubRepoParams) ([]*Repo, error) {
	rows, err := q.db.Query(ctx, listReposByGithubRepo, arg.GithubInstallationID, arg.Lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Provider,
			&i.GitUrl,
			&i.Branch,
			&i.AuthTokenEnc,
			&i.GithubInstallationID,
			&i.GithubFullName,
			&i.Status,
			&i.ConfigYaml,
			&i.ConfigError,
			&i.LastCommitSha,
			&i.LastSyncedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposForOrg = `-- name: ListReposForOrg :many
SELECT id, org_id, name, provider, git_url, branch, auth_token_enc, github_installation_id, github_full_name, status, config_yaml, config_error, last_commit_sha, last_synced_at, created_by, created_at, updated_at FROM repos WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListReposForOrg(ctx context.Context, orgID uuid.UUID) ([]*Repo, error) {
	rows, err := q.db.Query(ctx, listReposForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Provider,
			&i.GitUrl,
			&i.Branch,
			&i.AuthTokenEnc,
			&i.GithubInstallationID,
			&i.GithubFullName,
			&i.Status,
			&i.ConfigYaml,
			&i.ConfigError,
			&i.LastCommitSha,
			&i.LastSyncedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunDeployInputsForRuns = `-- name: ListRunDeployInputsForRuns :many
SELECT run_id, idx, name, label, value_enc, is_secret, deploy_time, source FROM run_inputs
WHERE run_id = ANY($1::uuid[]) AND deploy_time = true AND is_secret = false
ORDER BY run_id, idx
`

func (q *Queries) ListRunDeployInputsForRuns(ctx context.Context, dollar_1 []uuid.UUID) ([]*RunInput, error) {
	rows, err := q.db.Query(ctx, listRunDeployInputsForRuns, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RunInput
	for rows.Next() {
		var i RunInput
		if err := rows.Scan(
			&i.RunID,
			&i.Idx,
			&i.Name,
			&i.Label,
			&i.ValueEnc,
			&i.IsSecret,
			&i.DeployTime,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunInputs = `-- name: ListRunInputs :many
SELECT run_id, idx, name, label, value_enc, is_secret, deploy_time, source FROM run_inputs WHERE run_id = $1 ORDER BY idx
`

func (q *Queries) ListRunInputs(ctx context.Context, runID uuid.UUID) ([]*RunInput, error) {
	rows, err := q.db.Query(ctx, listRunInputs, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RunInput
	for rows.Next() {
		var i RunInput
		if err := rows.Scan(
			&i.RunID,
			&i.Idx,
			&i.Name,
			&i.Label,
			&i.ValueEnc,
			&i.IsSecret,
			&i.DeployTime,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunLogs = `-- name: ListRunLogs :many
SELECT run_id, seq, line, created_at FROM run_logs WHERE run_id = $1 ORDER BY seq
`

func (q *Queries) ListRunLogs(ctx context.Context, runID uuid.UUID) ([]*RunLog, error) {
	rows, err := q.db.Query(ctx, listRunLogs, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RunLog
	for rows.Next() {
		var i RunLog
		if err := rows.Scan(
			&i.RunID,
			&i.Seq,
			&i.Line,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunLogsAfter = `-- name: ListRunLogsAfter :many
SELECT run_id, seq, line, created_at FROM run_logs WHERE run_id = $1 AND seq > $2 ORDER BY seq
`

type ListRunLogsAfterParams struct {
	RunID uuid.UUID
	Seq   int32
}

func (q *Queries) ListRunLogsAfter(ctx context.Context, arg ListRunLogsAfterParams) ([]*RunLog, error) {
	rows, err := q.db.Query(ctx, listRunLogsAfter, arg.RunID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RunLog
	for rows.Next() {
		var i RunLog
		if err := rows.Scan(
			&i.RunID,
			&i.Seq,
			&i.Line,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunOutputs = `-- name: ListRunOutputs :many
SELECT run_id, name, value_enc, is_secret, created_at FROM run_outputs WHERE run_id = $1 ORDER BY name
`

func (q *Queries) ListRunOutputs(ctx context.Context, runID uuid.UUID) ([]*RunOutput, error) {
	rows, err := q.db.Query(ctx, listRunOutputs, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RunOutput
	for rows.Next() {
		var i RunOutput
		if err := rows.Scan(
			&i.RunID,
			&i.Name,
			&i.ValueEnc,
			&i.IsSecret,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunSteps = `-- name: ListRunSteps :many
SELECT run_id, idx, name, status FROM run_steps WHERE run_id = $1 ORDER BY idx
`

func (q *Queries) ListRunSteps(ctx context.Context, runID uuid.UUID) ([]*RunStep, error) {
	rows, err := q.db.Query(ctx, listRunSteps, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RunStep
	for rows.Next() {
		var i RunStep
		if err := rows.Scan(
			&i.RunID,
			&i.Idx,
			&i.Name,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsForOrg = `-- name: ListRunsForOrg :many
SELECT r.id, r.repo_id, r.target_id, r.deployment, r.target_name, r.status, r.trigger_kind, r.commit_sha, r.exit_code, r.failed_step, r.error, r.started_by, r.created_at, r.started_at, r.finished_at, rp.name AS repo_name
FROM runs r
JOIN repos rp ON rp.id = r.repo_id
WHERE rp.org_id = $1
ORDER BY r.created_at DESC, r.id DESC
LIMIT $2
`

type ListRunsForOrgParams struct {
	OrgID uuid.UUID
	Limit int32
}

type ListRunsForOrgRow struct {
	ID          uuid.UUID
	RepoID      uuid.UUID
	TargetID    uuid.NullUUID
	Deployment  string
	TargetName  string
	Status      string
	TriggerKind string
	CommitSha   string
	ExitCode    pgtype.Int4
	FailedStep  pgtype.Int4
	Error       string
	StartedBy   uuid.NullUUID
	CreatedAt   time.Time
	StartedAt   *time.Time
	FinishedAt  *time.Time
	RepoName    string
}

func (q *Queries) ListRunsForOrg(ctx context.Context, arg ListRunsForOrgParams) ([]*ListRunsForOrgRow, error) {
	rows, err := q.db.Query(ctx, listRunsForOrg, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListRunsForOrgRow
	for rows.Next() {
		var i ListRunsForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.TargetID,
			&i.Deployment,
			&i.TargetName,
			&i.Status,
			&i.TriggerKind,
			&i.CommitSha,
			&i.ExitCode,
			&i.FailedStep,
			&i.Error,
			&i.StartedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.RepoName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsForRepo = `-- name: ListRunsForRepo :many
SELECT id, repo_id, target_id, deployment, target_name, status, trigger_kind, commit_sha, exit_code, failed_step, error, started_by, created_at, started_at, finished_at FROM runs WHERE repo_id = $1 ORDER BY created_at DESC, id DESC LIMIT $2
`

type ListRunsForRepoParams struct {
	RepoID uuid.UUID
	Limit  int32
}

func (q *Queries) ListRunsForRepo(ctx context.Context, arg ListRunsForRepoParams) ([]*Run, error) {
	rows, err := q.db.Query(ctx, listRunsForRepo, arg.RepoID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.TargetID,
			&i.Deployment,
			&i.TargetName,
			&i.Status,
			&i.TriggerKind,
			&i.CommitSha,
			&i.ExitCode,
			&i.FailedStep,
			&i.Error,
			&i.StartedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsForTarget = `-- name: ListRunsForTarget :many
SELECT id, repo_id, target_id, deployment, target_name, status, trigger_kind, commit_sha, exit_code, failed_step, error, started_by, created_at, started_at, finished_at FROM runs WHERE target_id = $1 ORDER BY created_at DESC, id DESC LIMIT $2
`

type ListRunsForTargetParams struct {
	TargetID uuid.NullUUID
	Limit    int32
}

func (q *Queries) ListRunsForTarget(ctx context.Context, arg ListRunsForTargetParams) ([]*Run, error) {
	rows, err := q.db.Query(ctx, listRunsForTarget, arg.TargetID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.TargetID,
			&i.Deployment,
			&i.TargetName,
			&i.Status,
			&i.TriggerKind,
			&i.CommitSha,
			&i.ExitCode,
			&i.FailedStep,
			&i.Error,
			&i.StartedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetValues = `-- name: ListTargetValues :many
SELECT target_id, var_name, value_enc, is_secret, updated_by, updated_at FROM target_values WHERE target_id = $1 ORDER BY var_name
`

func (q *Queries) ListTargetValues(ctx context.Context, targetID uuid.UUID) ([]*TargetValue, error) {
	rows, err := q.db.Query(ctx, listTargetValues, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TargetValue
	for rows.Next() {
		var i TargetValue
		if err := rows.Scan(
			&i.TargetID,
			&i.VarName,
			&i.ValueEnc,
			&i.IsSecret,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetsForDeployment = `-- name: ListTargetsForDeployment :many
SELECT id, repo_id, deployment, name, description, auto_deploy, created_by, created_at, updated_at FROM targets WHERE repo_id = $1 AND deployment = $2 ORDER BY name
`

type ListTargetsForDeploymentParams struct {
	RepoID     uuid.UUID
	Deployment string
}

func (q *Queries) ListTargetsForDeployment(ctx context.Context, arg ListTargetsForDeploymentParams) ([]*Target, error) {
	rows, err := q.db.Query(ctx, listTargetsForDeployment, arg.RepoID, arg.Deployment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Deployment,
			&i.Name,
			&i.Description,
			&i.AutoDeploy,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetsForRepo = `-- name: ListTargetsForRepo :many
SELECT id, repo_id, deployment, name, description, auto_deploy, created_by, created_at, updated_at FROM targets WHERE repo_id = $1 ORDER BY deployment, name
`

func (q *Queries) ListTargetsForRepo(ctx context.Context, repoID uuid.UUID) ([]*Target, error) {
	rows, err := q.db.Query(ctx, listTargetsForRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Deployment,
			&i.Name,
			&i.Description,
			&i.AutoDeploy,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInterruptedRuns = `-- name: MarkInterruptedRuns :exec
UPDATE runs
SET status = 'failed', error = 'interrupted: the server was stopped while the run was in progress', finished_at = now()
WHERE status IN ('queued', 'building', 'running')
`

func (q *Queries) MarkInterruptedRuns(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markInterruptedRuns)
	return err
}

const pruneDeliveries = `-- name: PruneDeliveries :exec
DELETE FROM notification_deliveries d
WHERE d.org_id = $1 AND d.id NOT IN (
    SELECT k.id FROM notification_deliveries k WHERE k.org_id = $1 ORDER BY k.created_at DESC, k.id DESC LIMIT $2
)
`

type PruneDeliveriesParams struct {
	OrgID uuid.UUID
	Limit int32
}

func (q *Queries) PruneDeliveries(ctx context.Context, arg PruneDeliveriesParams) error {
	_, err := q.db.Exec(ctx, pruneDeliveries, arg.OrgID, arg.Limit)
	return err
}

const setOrgSMTPTest = `-- name: SetOrgSMTPTest :exec
UPDATE org_smtp_settings SET last_test_at = now(), last_test_error = $2 WHERE org_id = $1
`

type SetOrgSMTPTestParams struct {
	OrgID         uuid.UUID
	LastTestError string
}

func (q *Queries) SetOrgSMTPTest(ctx context.Context, arg SetOrgSMTPTestParams) error {
	_, err := q.db.Exec(ctx, setOrgSMTPTest, arg.OrgID, arg.LastTestError)
	return err
}

const setRunCommit = `-- name: SetRunCommit :exec
UPDATE runs SET commit_sha = $2 WHERE id = $1
`

type SetRunCommitParams struct {
	ID        uuid.UUID
	CommitSha string
}

func (q *Queries) SetRunCommit(ctx context.Context, arg SetRunCommitParams) error {
	_, err := q.db.Exec(ctx, setRunCommit, arg.ID, arg.CommitSha)
	return err
}

const setRunStatus = `-- name: SetRunStatus :exec
UPDATE runs SET status = $2 WHERE id = $1
`

type SetRunStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetRunStatus(ctx context.Context, arg SetRunStatusParams) error {
	_, err := q.db.Exec(ctx, setRunStatus, arg.ID, arg.Status)
	return err
}

const setRunStepStatus = `-- name: SetRunStepStatus :exec
UPDATE run_steps SET status = $3 WHERE run_id = $1 AND idx = $2
`

type SetRunStepStatusParams struct {
	RunID  uuid.UUID
	Idx    int32
	Status string
}

func (q *Queries) SetRunStepStatus(ctx context.Context, arg SetRunStepStatusParams) error {
	_, err := q.db.Exec(ctx, setRunStepStatus, arg.RunID, arg.Idx, arg.Status)
	return err
}

const skipUnfinishedRunSteps = `-- name: SkipUnfinishedRunSteps :exec
UPDATE run_steps SET status = 'skipped'
WHERE run_id = $1 AND status IN ('pending', 'running')
`

func (q *Queries) SkipUnfinishedRunSteps(ctx context.Context, runID uuid.UUID) error {
	_, err := q.db.Exec(ctx, skipUnfinishedRunSteps, runID)
	return err
}

const startRun = `-- name: StartRun :exec
UPDATE runs SET status = $2, started_at = now() WHERE id = $1
`

type StartRunParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) StartRun(ctx context.Context, arg StartRunParams) error {
	_, err := q.db.Exec(ctx, startRun, arg.ID, arg.Status)
	return err
}

const updateOrgMember = `-- name: UpdateOrgMember :one
UPDATE org_members SET role = $3, can_configure = $4, can_deploy = $5
WHERE org_id = $1 AND user_id = $2
RETURNING org_id, user_id, role, can_configure, can_deploy, created_at
`

type UpdateOrgMemberParams struct {
	OrgID        uuid.UUID
	UserID       uuid.UUID
	Role         string
	CanConfigure bool
	CanDeploy    bool
}

func (q *Queries) UpdateOrgMember(ctx context.Context, arg UpdateOrgMemberParams) (*OrgMember, error) {
	row := q.db.QueryRow(ctx, updateOrgMember,
		arg.OrgID,
		arg.UserID,
		arg.Role,
		arg.CanConfigure,
		arg.CanDeploy,
	)
	var i OrgMember
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CanConfigure,
		&i.CanDeploy,
		&i.CreatedAt,
	)
	return &i, err
}

const updateOrgName = `-- name: UpdateOrgName :one
UPDATE orgs SET name = $2 WHERE id = $1
RETURNING id, slug, name, personal, created_by, created_at
`

type UpdateOrgNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateOrgName(ctx context.Context, arg UpdateOrgNameParams) (*Org, error) {
	row := q.db.QueryRow(ctx, updateOrgName, arg.ID, arg.Name)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Personal,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const updateRecipient = `-- name: UpdateRecipient :exec
UPDATE notification_recipients SET email = $3, events = $4, enabled = $5, include_insight = $6, updated_at = now()
WHERE id = $1 AND org_id = $2
`

type UpdateRecipientParams struct {
	ID             uuid.UUID
	OrgID          uuid.UUID
	Email          string
	Events         []string
	Enabled        bool
	IncludeInsight bool
}

func (q *Queries) UpdateRecipient(ctx context.Context, arg UpdateRecipientParams) error {
	_, err := q.db.Exec(ctx, updateRecipient,
		arg.ID,
		arg.OrgID,
		arg.Email,
		arg.Events,
		arg.Enabled,
		arg.IncludeInsight,
	)
	return err
}

const updateRepoSettings = `-- name: UpdateRepoSettings :one
UPDATE repos
SET name = $2, branch = $3, git_url = $4, auth_token_enc = $5, updated_at = now()
WHERE id = $1
RETURNING id, org_id, name, provider, git_url, branch, auth_token_enc, github_installation_id, github_full_name, status, config_yaml, config_error, last_commit_sha, last_synced_at, created_by, created_at, updated_at
`

type UpdateRepoSettingsParams struct {
	ID           uuid.UUID
	Name         string
	Branch       string
	GitUrl       string
	AuthTokenEnc []byte
}

func (q *Queries) UpdateRepoSettings(ctx context.Context, arg UpdateRepoSettingsParams) (*Repo, error) {
	row := q.db.QueryRow(ctx, updateRepoSettings,
		arg.ID,
		arg.Name,
		arg.Branch,
		arg.GitUrl,
		arg.AuthTokenEnc,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Provider,
		&i.GitUrl,
		&i.Branch,
		&i.AuthTokenEnc,
		&i.GithubInstallationID,
		&i.GithubFullName,
		&i.Status,
		&i.ConfigYaml,
		&i.ConfigError,
		&i.LastCommitSha,
		&i.LastSyncedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateRepoSync = `-- name: UpdateRepoSync :exec
UPDATE repos
SET status = $2, config_yaml = $3, config_error = $4, last_commit_sha = $5,
    last_synced_at = now(), updated_at = now()
WHERE id = $1
`

type UpdateRepoSyncParams struct {
	ID            uuid.UUID
	Status        string
	ConfigYaml    string
	ConfigError   string
	LastCommitSha string
}

func (q *Queries) UpdateRepoSync(ctx context.Context, arg UpdateRepoSyncParams) error {
	_, err := q.db.Exec(ctx, updateRepoSync,
		arg.ID,
		arg.Status,
		arg.ConfigYaml,
		arg.ConfigError,
		arg.LastCommitSha,
	)
	return err
}

const updateTarget = `-- name: UpdateTarget :one
UPDATE targets SET name = $2, description = $3, auto_deploy = $4, updated_at = now()
WHERE id = $1
RETURNING id, repo_id, deployment, name, description, auto_deploy, created_by, created_at, updated_at
`

type UpdateTargetParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	AutoDeploy  bool
}

func (q *Queries) UpdateTarget(ctx context.Context, arg UpdateTargetParams) (*Target, error) {
	row := q.db.QueryRow(ctx, updateTarget,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.AutoDeploy,
	)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Deployment,
		&i.Name,
		&i.Description,
		&i.AutoDeploy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET name = $2, updated_at = now() WHERE id = $1
RETURNING id, email, name, password_hash, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertGithubInstallation = `-- name: UpsertGithubInstallation :exec

INSERT INTO github_installations (installation_id, account_login, account_type)
VALUES ($1, $2, $3)
ON CONFLICT (installation_id)
DO UPDATE SET account_login = excluded.account_login, account_type = excluded.account_type
`

type UpsertGithubInstallationParams struct {
	InstallationID int64
	AccountLogin   string
	AccountType    string
}

// GitHub installations -------------------------------------------------------
func (q *Queries) UpsertGithubInstallation(ctx context.Context, arg UpsertGithubInstallationParams) error {
	_, err := q.db.Exec(ctx, upsertGithubInstallation, arg.InstallationID, arg.AccountLogin, arg.AccountType)
	return err
}

const upsertOrgAI = `-- name: UpsertOrgAI :exec
INSERT INTO org_ai_settings (org_id, base_url, api_key_enc, model, verified_at, updated_by)
VALUES ($1, $2, $3, $4, now(), $5)
ON CONFLICT (org_id) DO UPDATE SET
    base_url = excluded.base_url, api_key_enc = excluded.api_key_enc, model = excluded.model,
    verified_at = now(), updated_by = excluded.updated_by, updated_at = now()
`

type UpsertOrgAIParams struct {
	OrgID     uuid.UUID
	BaseUrl   string
	ApiKeyEnc []byte
	Model     string
	UpdatedBy uuid.NullUUID
}

func (q *Queries) UpsertOrgAI(ctx context.Context, arg UpsertOrgAIParams) error {
	_, err := q.db.Exec(ctx, upsertOrgAI,
		arg.OrgID,
		arg.BaseUrl,
		arg.ApiKeyEnc,
		arg.Model,
		arg.UpdatedBy,
	)
	return err
}

const upsertOrgSMTP = `-- name: UpsertOrgSMTP :exec
INSERT INTO org_smtp_settings (org_id, host, port, username, password_enc, encryption, from_address, from_name, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (org_id) DO UPDATE SET
    host = excluded.host, port = excluded.port, username = excluded.username,
    password_enc = excluded.password_enc, encryption = excluded.encryption,
    from_address = excluded.from_address, from_name = excluded.from_name,
    updated_by = excluded.updated_by, updated_at = now()
`

type UpsertOrgSMTPParams struct {
	OrgID       uuid.UUID
	Host        string
	Port        int32
	Username    string
	PasswordEnc []byte
	Encryption  string
	FromAddress string
	FromName    string
	UpdatedBy   uuid.NullUUID
}

func (q *Queries) UpsertOrgSMTP(ctx context.Context, arg UpsertOrgSMTPParams) error {
	_, err := q.db.Exec(ctx, upsertOrgSMTP,
		arg.OrgID,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.PasswordEnc,
		arg.Encryption,
		arg.FromAddress,
		arg.FromName,
		arg.UpdatedBy,
	)
	return err
}

const upsertRunInsight = `-- name: UpsertRunInsight :exec
INSERT INTO run_insights (run_id, model, content, created_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (run_id) DO UPDATE SET
    model = excluded.model, content = excluded.content, created_by = excluded.created_by, created_at = now()
`

type UpsertRunInsightParams struct {
	RunID     uuid.UUID
	Model     string
	Content   string
	CreatedBy uuid.NullUUID
}

func (q *Queries) UpsertRunInsight(ctx context.Context, arg UpsertRunInsightParams) error {
	_, err := q.db.Exec(ctx, upsertRunInsight,
		arg.RunID,
		arg.Model,
		arg.Content,
		arg.CreatedBy,
	)
	return err
}

const upsertTargetValue = `-- name: UpsertTargetValue :exec

INSERT INTO target_values (target_id, var_name, value_enc, is_secret, updated_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (target_id, var_name)
DO UPDATE SET value_enc = excluded.value_enc,
              is_secret = excluded.is_secret,
              updated_by = excluded.updated_by,
              updated_at = now()
`

type UpsertTargetValueParams struct {
	TargetID  uuid.UUID
	VarName   string
	ValueEnc  []byte
	IsSecret  bool
	UpdatedBy uuid.NullUUID
}

// Target values --------------------------------------------------------------
func (q *Queries) UpsertTargetValue(ctx context.Context, arg UpsertTargetValueParams) error {
	_, err := q.db.Exec(ctx, upsertTargetValue,
		arg.TargetID,
		arg.VarName,
		arg.ValueEnc,
		arg.IsSecret,
		arg.UpdatedBy,
	)
	return err
}
